---
name: "Google Books"
guid: "7a9f4890-b216-4d75-a0e4-4c9f29ed5217"
version: 1
targetAbi: "10.11.0.0"
framework: "net9.0"
owner: "jellyfin"
overview: "Google Books Metadata Provider"
description: >
  Pulls book metadata and cover images from Google Books.
category: "Books"
artifacts:
  - "Jellyfin.Plugin.GoogleBooks.dll"
changelog: |-
  Initial Release
